name: Deploy Hugging Face Model to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install torch transformers boto3 sagemaker pd numpy

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Upload Model to S3
        run: |
          mkdir -p model
          python scripts/save_model.py  # Script to save model as `model.tar.gz`
          aws s3 cp model/model.tar.gz s3://your-bucket-name/model.tar.gz

      - name: Deploy to SageMaker
        run: python scripts/deploy_model.py
