name: Azure ML Model Registration and Deployment process


on:
  push:
    branches:
      - master # Trigger on push to main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  register-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml azure-identity transformers torch

      - name: Azure Login
        run: |
          az login --service-principal \
            -u "${{ secrets.AZURE_CLIENT_ID }}" \
            --password="${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Register Azure ML Services
        run: az provider register --namespace Microsoft.MachineLearningServices

      # Step 6: Deploy the model to an endpoint
      - name: Deploy the Model
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_ML_WORKSPACE_NAME: ${{ secrets.AZURE_ML_WORKSPACE_NAME }}
          
        run: |
          python -c "
          from azure.ai.ml import MLClient
          from azure.identity import ClientSecretCredential
          from azure.ai.ml.entities import ManagedOnlineEndpoint, ManagedOnlineDeployment
          import os

          # Load Azure ML workspace details from environment variables
          subscription_id = os.environ['AZURE_SUBSCRIPTION_ID']
          resource_group = os.environ['AZURE_RESOURCE_GROUP']
          workspace_name = os.environ['AZURE_ML_WORKSPACE_NAME']

          # Initialize MLClient with ClientSecretCredential
          credential = ClientSecretCredential(
              tenant_id=os.environ['AZURE_TENANT_ID'],
              client_id=os.environ['AZURE_CLIENT_ID'],
              client_secret=os.environ['AZURE_CLIENT_SECRET']
          )
          ml_client = MLClient(credential, subscription_id, resource_group, workspace_name)

          # Define endpoint and deployment
          endpoint_name = 'deberta-text-model'
          deployment_name = 'blue'
          model_name = 'credit_defaults_model'

          # Create or update endpoint
          endpoint = ManagedOnlineEndpoint(
              name=endpoint_name,
              auth_mode='key'
          )
          ml_client.online_endpoints.begin_create_or_update(endpoint).result()

          # Create deployment
          deployment = ManagedOnlineDeployment(
              name=deployment_name,
              endpoint_name=endpoint_name,
              model=model_name,
              instance_type='Standard_DS2_v2',
              instance_count=1
          )
          ml_client.online_deployments.begin_create_or_update(deployment).result()

          # Set traffic to 100% for the new deployment
          endpoint.traffic = {deployment_name: 100}
          ml_client.online_endpoints.begin_create_or_update(endpoint).result()

          print(f'Model deployed to endpoint: {endpoint_name}')
          "
