name: Local CI/CD Pipeline with DVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    name: Lint & Format Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install black flake8 mypy

      - name: Run Black (Code Formatting)
        run: black --check .

      - name: Run Flake8 (Linting)
        run: flake8 .

      - name: Run Mypy (Type Checking)
        run: mypy .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Tests
        run: pytest tests/

  train:
    name: Train Model with DVC
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install dvc dvc-gdrive

      - name: Pull Data from DVC
        run: dvc pull

      - name: Run Training Script
        run: dvc repro --downstream evaluate

      - name: Track Model with DVC
        run: |
          dvc add models/best_model
          git add models/best_model.dvc
          git commit -m "Track trained model with DVC"`