name: Local CI/CD Pipeline with DVC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  evaluate:
    name: Evaluate Model with DVC
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Configure DVC Remote
        run: |
          dvc remote add -d myremote s3://dvc-text-bucket
          dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc remote modify myremote region eu-north-1
          
      - name: Pull Data & Model from DVC
        run: |
          dvc pull  # Ensure we have all required files
          dvc status  # Show which files are missing or updated
          ls -R data/  # List all files in the data directory

      - name: Run Evaluation Script
        run: dvc repro  evaluate

