name: Local CI/CD Pipeline with DVC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  installing-required-parameters:
    name: Install Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Verify installed packages
        run: pip list

  lint-format:
    name: Lint & Format Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install black flake8 mypy ruff

      - name: Install Additional Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 mypy

      - name: Install Black for Jupyter
        run: pip install "black[jupyter]"

      - name: Run Black (Code Formatting)
        run: black src/ tests/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Configure DVC Remote
        run: |
          dvc remote add -d myremote s3://dvc-text-bucket
          dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc remote modify myremote region eu-north-1

      - name: Pull Data & Model from DVC
        run: dvc pull  # Fetch both dataset & model

      - name: Run Tests
        run: pytest tests/

  evaluate:
    name: Evaluate Model with DVC
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Configure DVC Remote
        run: |
          dvc remote add -d myremote s3://dvc-text-bucket
          dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc remote modify myremote region eu-north-1

      - name: Pull Data & Model from DVC
        run: dvc pull  # Ensure we have all required files

      - name: Run Evaluation Script
        run: dvc repro  evaluate

